name: offline_first
description: offline first app example.

publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  blue_thermal_printer: ^1.2.3
  bluetooth_print: ^4.3.0
  camera: ^0.10.5+5
  dio: ^5.3.2
  equatable: ^2.0.5
  file_picker: ^5.3.2
  fluentui_system_icons: ^1.1.217
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_dotenv: ^5.0.2
  flutter_inappwebview: ^5.8.0
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.3.2
  formz: ^0.6.0
  geolocator: ^9.0.2
  go_router: ^7.1.1
  http: ^1.1.0
  image_picker: ^1.0.4
  internet_connection_checker: ^1.0.0+1
  internet_connection_checker_plus: ^2.0.0
  intl: ^0.18.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  just_audio: ^0.9.34
  mobile_scanner: ^3.2.0
  open_filex: ^4.3.4
  path: ^1.8.3
  path_provider: ^2.0.15
  permission_handler: ^10.3.0
  qr_code_scanner: ^1.0.1
  record: ^4.4.4
  share_plus: ^7.2.1
  shared_preferences: ^2.2.0
  torch_light: ^1.0.0
  url_launcher: ^6.1.14
  uuid: ^4.1.0
  provider: ^6.0.5
  barcode_image: ^2.0.2
  image: ^4.1.3
  fluttertoast: ^8.2.2

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  isar_generator: ^3.1.0+1

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/sanel_logo_simbol.png
  color_dark: "#ffffff"
  image_dark: assets/images/sanel_logo_simbol.png
  fullscreen: true

  android_12:
    image: assets/images/sanel_logo_simbol.png
    icon_background_color: "#ffffff"
    image_dark: assets/images/sanel_logo_simbol.png
    icon_background_color_dark: "#ffffff"

  web: false

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/audios/
    - .env

  fonts:
    - family: SF-Pro-Display
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Regular.ttf
          weight: 400
        - asset: assets/fonts/SF-Pro-Display-Light.ttf
          weight: 300
        - asset: assets/fonts/SF-Pro-Display-Medium.ttf
          weight: 500
        - asset: assets/fonts/SF-Pro-Display-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/SF-Pro-Display-Bold.otf
          weight: 700
